### PR TITLE
GWR

### PR DESCRIPTION
**Pull request by TaylorOshan**
Looked around the GWR4 code a bit and noticed that the isle weight we were using does't match the weight function for fixed gaussian bandwidth in GWR4. Put together a quick version of the GWR4-based weight and it looks like the baseGWR estimated coefficients now match those from GWR4 and spgwr. Haven't made the same updates to gwr.py yet.

### CODE REVIEW

**Comment by ljwolf** [comment]
Gonna pull this down and check it out first. I hate that there's no cell-by-cell diff for viewing notebooks in github diffs...

**Comment by ljwolf** [comment]
Huh... so what's the difference between the formulations?

**Comment by TaylorOshan** [comment]
I'm not 100% sure, but I noticed that for the Kernel function we were using from pysal that the bandwidth parameter isn't the same as in the GWR softwares. i.e., pysal bandwidth defines number of nearest neighbors (we used 3) from which to derive the distance for the weighting function (I think it spit out something like .85) , whereas the GWR4 bandwidth directly uses three within the weighting function. Also, I think the actual gaussian weighting function are different. In the pysal documentation I am seeing

K(z) = (2\pi)^{(-1/2)} exp(-z^2 / 2)

where z is a bandwidth derived based on some number of nearest neighbors (specified with bandwidth argument).

In contrast, in GWR4 the function is 

W = np.exp(-0.5*(dists/bandwidth)**2)

where lists are distance between pairwise observations and bandwidth is actually the bandwidth of the weighting function. 

I only looked quickly, but I didn't see any equivalent formulation in pysal, so I just put something quick together in order to have some validation.

**Comment by TaylorOshan** [comment]
As far as changes in baseGWR, I only had to change the way the way that weights are accessed since it was longer using a pysal weights object. I also removed the sqrt function, which it appears it not necessary, at least for a basic gaussian GWR. Still not sure why that is happening in the GWR4 code, but it must have something to do with the IRLS algorithm, which I don't think ends up applying to the gaussian GWR.

**Comment by ljwolf** [comment]
Ahh, so the issue was still with the weighting algorithm...

I hoped that's where it was... I thought the math we did was solid.

So, that's a fixed-bandwidth. Implementations could move GWSAR or to FBGWR.
Let's meet up about this and see how easy it would be to modify the
existing GM_Lag class to do what we want in GWSAR. I know I was looking at
it and getting issues with 1 for self-weights...

**Pull request merged**
